"""add new fields to favorites

Revision ID: 363a10ef3905
Revises: 53a11a7a843b
Create Date: 2025-11-04 17:36:40.810365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363a10ef3905'
down_revision: Union[str, Sequence[str], None] = '53a11a7a843b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('damage_pr', sa.String(), nullable=True))
    op.add_column('favorites', sa.Column('damage_sec', sa.String(), nullable=True))
    op.add_column('favorites', sa.Column('fuel', sa.String(), nullable=True))
    op.add_column('favorites', sa.Column('transmission', sa.String(), nullable=True))
    op.add_column('favorites', sa.Column('engine_size', sa.String(), nullable=True))
    op.add_column('favorites', sa.Column('cylinders', sa.String(), nullable=True))
    op.add_column('favorites', sa.Column('seller', sa.String(), nullable=True))
    op.add_column('favorites', sa.Column('document', sa.String(), nullable=True))
    op.add_column('favorites', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('favorites', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('favorites', 'auction_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('favorites', 'vin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('favorites', 'images',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('favorites', 'odometer',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('favorites', 'damage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('damage', sa.VARCHAR(), nullable=False))
    op.alter_column('favorites', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('favorites', 'odometer',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'images',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('favorites', 'vin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('favorites', 'auction_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('favorites', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('favorites', 'status')
    op.drop_column('favorites', 'document')
    op.drop_column('favorites', 'seller')
    op.drop_column('favorites', 'cylinders')
    op.drop_column('favorites', 'engine_size')
    op.drop_column('favorites', 'transmission')
    op.drop_column('favorites', 'fuel')
    op.drop_column('favorites', 'damage_sec')
    op.drop_column('favorites', 'damage_pr')
    # ### end Alembic commands ###
