"""init

Revision ID: 77a64465eed2
Revises: 
Create Date: 2025-10-17 15:46:59.731328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a64465eed2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('auction', sa.Enum('COPART', 'IAAI', name='auctions'), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('auction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('images', sa.String(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('damage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
